apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-glue
  labels:
    app: devops-glue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-glue
  template:
    metadata:
      labels:
        app: devops-glue
    spec:
      imagePullSecrets:
        - name: harbor-regcred
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: devops-glue
          image: 192.168.137.5/mycode/devops-glue:{TAG}
          ports:
            - containerPort: 80
          env:
            - name: DB_DRIVER
              value: "mysql"
            - name: DB_HOST
              value: "192.168.137.5"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "devops_glue"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "123456"
---
apiVersion: v1
kind: Service
metadata:
  name: devops-glue
spec:
  type: NodePort
  selector:
    app: devops-glue
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
